# Generated by Django 6.0.6 on 2026-06-29 21:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='journalaudit',
            name='utilisateur',
        ),
        migrations.DeleteModel(
            name='Delegation',
        ),
        migrations.DeleteModel(
            name='JournalAudit',
        ),
    ]
