# Generated by Django 6.0.6 on 2026-06-29 21:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courriers', '0001_initial'),
        ('dashboard', '0002_remove_journalaudit_utilisateur_delete_delegation_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Delegation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('perimetre', models.CharField(choices=[('COURRIER', 'Un courrier specifique'), ('PERIODE', 'Une periode donnee'), ('FONDS', 'Un fonds d archive'), ('DOSSIER', 'Un dossier thematique')], max_length=15)),
                ('motif', models.TextField()),
                ('periode_debut', models.DateField(blank=True, null=True)),
                ('periode_fin_perim', models.DateField(blank=True, null=True)),
                ('fonds_vise', models.CharField(blank=True, max_length=10)),
                ('dossier_thematique', models.CharField(blank=True, max_length=255)),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
                ('active', models.BooleanField(default=True)),
                ('date_revocation', models.DateTimeField(blank=True, null=True)),
                ('motif_revocation', models.TextField(blank=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('accordee_par', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='delegations_accordees', to=settings.AUTH_USER_MODEL)),
                ('beneficiaire', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='delegations_recues', to=settings.AUTH_USER_MODEL)),
                ('courrier_vise', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='delegations', to='courriers.courrier')),
            ],
            options={
                'verbose_name': 'Delegation',
                'verbose_name_plural': 'Delegations',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='JournalAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horodatage_utc', models.DateTimeField(auto_now_add=True)),
                ('identifiant_user', models.CharField(blank=True, max_length=50)),
                ('profil_user', models.CharField(blank=True, max_length=10)),
                ('type_action', models.CharField(choices=[('SAISIE', 'Saisie de courrier'), ('SOUMISSION', 'Soumission a verification'), ('MODIFICATION', 'Modification de courrier'), ('VALIDATION', 'Validation de courrier'), ('REJET', 'Rejet de courrier'), ('IMPUTATION', 'Imputation de courrier'), ('CONSULTATION', 'Consultation de courrier'), ('TELECHARGEMENT', 'Telechargement de document'), ('TRAITEMENT', 'Traitement de courrier'), ('ARCHIVAGE', 'Archivage de courrier'), ('CREATION_COMPTE', 'Creation de compte'), ('MODIF_COMPTE', 'Modification de compte'), ('DESACT_COMPTE', 'Desactivation de compte'), ('DELEG_ACCORD', 'Delegation accordee'), ('DELEG_REVOQUE', 'Delegation revoquee'), ('DELEG_UTIL', 'Delegation utilisee'), ('CONNEXION', 'Connexion'), ('ACCES_REFUSE', 'Acces refuse'), ('VERSEMENT', 'Versement d archive')], max_length=20)),
                ('description', models.TextField()),
                ('objet_type', models.CharField(blank=True, max_length=50)),
                ('objet_id', models.CharField(blank=True, max_length=100)),
                ('objet_libelle', models.CharField(blank=True, max_length=500)),
                ('adresse_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('terminal', models.CharField(blank=True, max_length=255)),
                ('issue', models.CharField(choices=[('SUCCES', 'Succes'), ('REFUS', 'Refus'), ('ERREUR', 'Erreur')], default='SUCCES', max_length=10)),
                ('utilisateur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actions_audit', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Journal d audit',
                'verbose_name_plural': 'Journal d audit',
                'ordering': ['-horodatage_utc'],
                'default_permissions': ('view',),
            },
        ),
    ]
