# Generated by Django 6.0.7 on 2026-07-22 22:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_initial'),
        ('organisations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='journalaudit',
            options={'ordering': ['-horodatage_utc']},
        ),
        migrations.RemoveField(
            model_name='journalaudit',
            name='objet_libelle',
        ),
        migrations.AddField(
            model_name='journalaudit',
            name='objet_label',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='journalaudit',
            name='organisation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='journal_audit', to='organisations.organisation'),
        ),
        migrations.AlterField(
            model_name='journalaudit',
            name='issue',
            field=models.CharField(choices=[('SUCCES', 'Succès'), ('ECHEC', 'Échec'), ('REFUS', 'Refus')], default='SUCCES', max_length=10),
        ),
        migrations.AlterField(
            model_name='journalaudit',
            name='type_action',
            field=models.CharField(choices=[('CONNEXION', 'Connexion'), ('SOUMISSION', 'Soumission'), ('VALIDATION', 'Validation'), ('REJET', 'Rejet'), ('IMPUTATION', 'Imputation'), ('CONSULTATION', 'Consultation'), ('TRAITEMENT', 'Traitement'), ('ARCHIVAGE', 'Archivage'), ('MODIF_COMPTE', 'Modification compte'), ('CREATION_COMPTE', 'Création compte'), ('DESACT_COMPTE', 'Désactivation compte')], max_length=20),
        ),
        migrations.AlterField(
            model_name='journalaudit',
            name='utilisateur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Delegation',
        ),
    ]
