# Generated by Django 6.0.3 on 2026-06-13 21:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ArchiveHistorique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_systeme', models.CharField(blank=True, max_length=30, unique=True)),
                ('reference_origine', models.CharField(blank=True, max_length=200)),
                ('fonds', models.CharField(choices=[('ESCEP', 'ESCEP (2023-present)'), ('EST', 'EST (2011-2023)'), ('CNIPT', 'CNIPT (1969-2011)'), ('AUTRE', 'Autre fonds')], max_length=10)),
                ('type_document', models.CharField(choices=[('LETTRE', 'Lettre'), ('ARRETE', 'Arrete'), ('DECRET', 'Decret'), ('NOTE', 'Note de service'), ('CONVENTION', 'Convention'), ('RAPPORT', 'Rapport'), ('CIRCULAIRE', 'Circulaire'), ('AUTRE', 'Autre')], default='LETTRE', max_length=15)),
                ('intitule', models.CharField(max_length=500)),
                ('expediteur', models.CharField(blank=True, max_length=255)),
                ('date_document', models.DateField()),
                ('categorie', models.CharField(blank=True, max_length=200)),
                ('mots_cles', models.TextField(blank=True, help_text='Mots-cles separes par des virgules')),
                ('resume', models.TextField(blank=True)),
                ('fichier', models.FileField(upload_to='archives/%Y/%m/')),
                ('contenu_ocr', models.TextField(blank=True, help_text='Texte extrait automatiquement par OCR')),
                ('lot', models.CharField(blank=True, help_text='Identifiant du lot si versement par lot', max_length=100)),
                ('date_versement', models.DateTimeField(auto_now_add=True)),
                ('est_historique', models.BooleanField(default=True)),
                ('verse_par', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='archives_versees', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Archive historique',
                'verbose_name_plural': 'Archives historiques',
                'ordering': ['-date_document'],
            },
        ),
    ]
