# Generated by Django 6.0.6 on 2026-06-29 21:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('archives', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ArchiveHistorique',
        ),
    ]
