# Generated by Django 6.0.7 on 2026-07-08 00:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Direction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200, unique=True)),
                ('sigle', models.CharField(blank=True, max_length=20)),
                ('description', models.TextField(blank=True)),
                ('active', models.BooleanField(default=True)),
                ('ordre', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Direction',
                'ordering': ['ordre', 'nom'],
            },
        ),
        migrations.CreateModel(
            name='ParametresApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_application', models.CharField(default='GED ESCEP-Niger', max_length=100)),
                ('slogan', models.CharField(default='Gestion Électronique des Documents', max_length=200)),
                ('texte_pied_page', models.CharField(default='© ESCEP-Niger — Système de Gestion Électronique des Documents', max_length=300)),
                ('couleur_principale', models.CharField(default='#1565C0', max_length=7)),
                ('couleur_accent', models.CharField(default='#FDD835', max_length=7)),
                ('couleur_danger', models.CharField(default='#D32F2F', max_length=7)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='parametres/')),
                ('image_fond_login', models.ImageField(blank=True, null=True, upload_to='parametres/')),
                ('timeout_inactivite', models.PositiveIntegerField(default=30, help_text='Minutes avant déconnexion automatique')),
                ('duree_validite_mdp', models.PositiveIntegerField(default=90, help_text='Jours avant expiration du mot de passe')),
                ('tentatives_max', models.PositiveIntegerField(default=5, help_text='Tentatives avant verrouillage')),
                ('double_auth_active', models.BooleanField(default=False, help_text='Activer la double authentification globalement')),
                ('email_expediteur', models.EmailField(blank=True, help_text='Email qui envoie les codes 2FA', max_length=254)),
                ('texte_email_2fa', models.TextField(default='Votre code de vérification GED ESCEP-Niger est : {code}\nCe code expire dans 10 minutes.', help_text="Texte de l'email 2FA. Utiliser {code} pour le code.")),
            ],
            options={
                'verbose_name': "Paramètres de l'application",
            },
        ),
        migrations.RemoveField(
            model_name='utilisateur',
            name='entite',
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='alerte_mdp_envoyee',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='code_2fa',
            field=models.CharField(blank=True, max_length=6),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='code_2fa_expiration',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='date_derniere_mdp',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='double_auth_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='double_auth_desactive_admin',
            field=models.BooleanField(default=False, help_text='Admin a désactivé la 2FA pour cet utilisateur'),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='modules_actifs',
            field=models.JSONField(blank=True, default=list, help_text='Liste des modules accessibles ex: ["courriers","archives"]'),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='tentatives_connexion',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='verrouille_jusqu',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='profil',
            field=models.CharField(choices=[('DG', 'Directeur Général'), ('ASSIST', 'Assistant DG'), ('BO', "Bureau d'Ordre"), ('DEST', 'Destinataire'), ('ARC', 'Archiviste'), ('ADMIN', 'Administrateur')], max_length=10),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='direction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='utilisateurs', to='users.direction'),
        ),
    ]
