# Generated by Django 6.0.7 on 2026-07-20 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_direction_parametresapplication_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='parametresapplication',
            name='flou_image_fond',
            field=models.PositiveIntegerField(default=5, help_text="Intensité du flou de l'image de fond en pixels (ex: 5)"),
        ),
    ]
