# Generated by Django 6.0.7 on 2026-07-22 22:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0001_initial'),
        ('users', '0003_parametresapplication_flou_image_fond'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ParametresApplication',
        ),
        migrations.AddField(
            model_name='direction',
            name='organisation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='directions', to='organisations.organisation'),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='organisation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='utilisateurs', to='organisations.organisation'),
        ),
        migrations.AlterField(
            model_name='direction',
            name='nom',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='double_auth_desactive_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='modules_actifs',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
