# Generated by Django 6.0.7 on 2026-07-23 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_delete_parametresapplication_direction_organisation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilisateur',
            name='profil',
            field=models.CharField(blank=True, choices=[('DG', 'Directeur Général'), ('ASSIST', 'Assistant DG'), ('BO', "Bureau d'Ordre"), ('DEST', 'Destinataire'), ('ARC', 'Archiviste'), ('ADMIN', 'Administrateur')], default='', max_length=10),
        ),
    ]
