# Generated by Django 6.0.7 on 2026-07-28 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_utilisateur_profil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilisateur',
            name='profil',
            field=models.CharField(blank=True, choices=[('DG', 'Directeur Général'), ('ASSIST', 'Assistant DG'), ('BO', "Bureau d'Ordre"), ('DEST', 'Destinataire'), ('ARC', 'Archiviste'), ('ADMIN', 'Administrateur'), ('SGA', 'Secrétaire Général Adjoint'), ('SG', 'Secrétaire Général')], default='', max_length=10),
        ),
    ]
