# Generated by Django 6.0.6 on 2026-06-11 22:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Courrier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifiant_temp', models.CharField(blank=True, max_length=30, null=True, unique=True)),
                ('numero_officiel', models.CharField(blank=True, max_length=30, null=True, unique=True)),
                ('type_courrier', models.CharField(choices=[('ENT', 'Courrier entrant'), ('INT', 'Courrier interne')], default='ENT', max_length=3)),
                ('mode_reception', models.CharField(choices=[('DEPOT', 'Depot direct'), ('POSTAL', 'Courrier postal'), ('EMAIL', 'Email imprime'), ('COURSIER', 'Coursier')], default='DEPOT', max_length=10)),
                ('priorite', models.CharField(choices=[('HAUTE', 'Haute'), ('NORMALE', 'Normale'), ('BASSE', 'Basse')], default='NORMALE', max_length=10)),
                ('statut', models.CharField(choices=[('BROUILLON', 'Brouillon'), ('EN_VERIF', 'En verification'), ('VERIFIE', 'Verifie'), ('REJETE', 'Rejete'), ('EN_ATT_IMP', 'En attente imputation'), ('IMPUTE', 'Impute'), ('EN_COURS', 'En cours de traitement'), ('TRAITE', 'Traite'), ('ARCHIVE', 'Archive')], default='BROUILLON', max_length=15)),
                ('objet', models.CharField(max_length=500)),
                ('expediteur', models.CharField(max_length=255)),
                ('reference_exp', models.CharField(blank=True, max_length=100)),
                ('date_document', models.DateField()),
                ('date_reception', models.DateField()),
                ('observations', models.TextField(blank=True)),
                ('fichier_pdf', models.FileField(upload_to='courriers/%Y/%m/')),
                ('date_saisie', models.DateTimeField(auto_now_add=True)),
                ('date_verification', models.DateTimeField(blank=True, null=True)),
                ('motif_rejet', models.TextField(blank=True)),
                ('observation_dg', models.TextField(blank=True)),
                ('date_imputation', models.DateTimeField(blank=True, null=True)),
                ('instructions_dg', models.TextField(blank=True)),
                ('date_traitement', models.DateTimeField(blank=True, null=True)),
                ('reponse_traitement', models.TextField(blank=True)),
                ('destinataire', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='courriers_recus', to=settings.AUTH_USER_MODEL)),
                ('impute_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='courriers_imputes', to=settings.AUTH_USER_MODEL)),
                ('saisi_par', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='courriers_saisis', to=settings.AUTH_USER_MODEL)),
                ('verifie_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='courriers_verifies', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Courrier',
                'verbose_name_plural': 'Courriers',
                'ordering': ['-date_saisie'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('lue', models.BooleanField(default=False)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('courrier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='courriers.courrier')),
                ('destinataire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='CourrierCopie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_lecture', models.DateTimeField(blank=True, null=True)),
                ('courrier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='copies', to='courriers.courrier')),
                ('destinataire', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='courriers_en_copie', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('courrier', 'destinataire')},
            },
        ),
    ]
