# Generated by Django 6.0.7 on 2026-07-22 22:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courriers', '0001_initial'),
        ('organisations', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='courrier',
            options={'ordering': ['-date_saisie']},
        ),
        migrations.AddField(
            model_name='courrier',
            name='organisation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='courriers', to='organisations.organisation'),
        ),
        migrations.AddField(
            model_name='courriercopie',
            name='organisation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='courrier_copies', to='organisations.organisation'),
        ),
        migrations.AddField(
            model_name='notification',
            name='organisation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='organisations.organisation'),
        ),
        migrations.AlterField(
            model_name='courrier',
            name='mode_reception',
            field=models.CharField(choices=[('DEPOT', 'Dépôt direct'), ('POSTAL', 'Courrier postal'), ('EMAIL', 'Email imprimé'), ('COURSIER', 'Coursier')], default='DEPOT', max_length=10),
        ),
        migrations.AlterField(
            model_name='courrier',
            name='statut',
            field=models.CharField(choices=[('BROUILLON', 'Brouillon'), ('EN_VERIF', 'En vérification'), ('VERIFIE', 'Vérifié'), ('REJETE', 'Rejeté'), ('EN_ATT_IMP', 'En attente imputation'), ('IMPUTE', 'Imputé'), ('EN_COURS', 'En cours de traitement'), ('TRAITE', 'Traité'), ('ARCHIVE', 'Archivé')], default='BROUILLON', max_length=15),
        ),
    ]
