# Generated by Django 6.0.7 on 2026-07-28 21:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courriers', '0002_alter_courrier_options_courrier_organisation_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='courrier',
            name='date_validation_sg',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='courrier',
            name='date_validation_sga',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='courrier',
            name='motif_rejet_sga',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='courrier',
            name='proposition_sg',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='courrier',
            name='proposition_sga',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='courrier',
            name='valide_sg_par',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='courriers_valides_sg', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='courrier',
            name='valide_sga_par',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='courriers_valides_sga', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='courrier',
            name='statut',
            field=models.CharField(choices=[('BROUILLON', 'Brouillon'), ('EN_VERIF', 'En vérification'), ('VERIFIE', 'Vérifié'), ('REJETE', 'Rejeté'), ('EN_ATT_IMP', 'En attente imputation'), ('IMPUTE', 'Imputé'), ('EN_COURS', 'En cours de traitement'), ('TRAITE', 'Traité'), ('ARCHIVE', 'Archivé'), ('EN_ATT_SGA', 'En attente SGA'), ('EN_ATT_SG', 'En attente SG')], default='BROUILLON', max_length=15),
        ),
    ]
