# Generated by Django 6.0.7 on 2026-07-28 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courriers', '0003_courrier_date_validation_sg_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courrier',
            name='priorite',
            field=models.CharField(choices=[('URGENT', 'Urgent'), ('NORMALE', 'Normale'), ('TRES_URGENT', 'Très urgent')], default='NORMALE', max_length=20),
        ),
    ]
