# Generated by Django 6.0.7 on 2026-07-29 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courriers', '0004_alter_courrier_priorite'),
    ]

    operations = [
        migrations.AddField(
            model_name='courrier',
            name='heure_depot',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
