# Generated by Django 6.0.7 on 2026-07-29 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courriers', '0005_courrier_heure_depot'),
    ]

    operations = [
        migrations.AddField(
            model_name='courrier',
            name='fichier_reponse',
            field=models.FileField(blank=True, null=True, upload_to='reponses/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='courriercopie',
            name='consigne_libre',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='courriercopie',
            name='consignes_types',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
