# Generated by Django 6.0.7 on 2026-08-02 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courriers', '0006_courrier_fichier_reponse_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='courriercopie',
            name='date_traitement',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='courriercopie',
            name='fichier_reponse',
            field=models.FileField(blank=True, null=True, upload_to='reponses_copie/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='courriercopie',
            name='reponse',
            field=models.TextField(blank=True),
        ),
    ]
