# Generated by Django 6.0.7 on 2026-07-22 22:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Organisation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_tenant', models.CharField(help_text='Slug unique (escep, ministere, universite, etc.)', max_length=50, unique=True)),
                ('nom', models.CharField(max_length=200)),
                ('slogan', models.CharField(blank=True, max_length=200)),
                ('texte_pied_page', models.CharField(blank=True, max_length=300)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='organisations/%Y/%m/')),
                ('image_fond_login', models.ImageField(blank=True, null=True, upload_to='organisations/%Y/%m/')),
                ('favicon', models.ImageField(blank=True, null=True, upload_to='organisations/%Y/%m/')),
                ('couleur_principale', models.CharField(default='#1565C0', max_length=7)),
                ('couleur_accent', models.CharField(default='#FDD835', max_length=7)),
                ('couleur_danger', models.CharField(default='#D32F2F', max_length=7)),
                ('flou_image_fond', models.PositiveIntegerField(default=5)),
                ('domaine_personnalise', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('active', models.BooleanField(default=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('max_utilisateurs', models.PositiveIntegerField(default=50)),
                ('max_stockage_go', models.PositiveIntegerField(default=100)),
                ('plan', models.CharField(choices=[('GRATUIT', 'Gratuit'), ('PRO', 'Pro'), ('ENTERPRISE', 'Entreprise')], default='GRATUIT', max_length=20)),
                ('date_fin_abonnement', models.DateField(blank=True, null=True)),
                ('timeout_inactivite', models.PositiveIntegerField(default=30)),
                ('duree_validite_mdp', models.PositiveIntegerField(default=90)),
                ('tentatives_max', models.PositiveIntegerField(default=5)),
                ('double_auth_active', models.BooleanField(default=False)),
                ('email_expediteur', models.EmailField(blank=True, max_length=254)),
                ('texte_email_2fa', models.TextField(default='Votre code de vérification est : {code}\nCe code expire dans 10 minutes.')),
                ('admin_principal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='organisations_administrees', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['nom'],
            },
        ),
    ]
