# Generated by Django 6.0.7 on 2026-07-26 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0002_add_typographie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organisation',
            name='couleur_texte',
            field=models.CharField(default='#222222', help_text='Couleur texte principal', max_length=7),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='couleur_texte_secondaire',
            field=models.CharField(default='#666666', help_text='Couleur texte secondaire/sous-titres', max_length=7),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='graisse_titres',
            field=models.CharField(default='700', help_text='Graisse des titres (500, 600, 700, 800)', max_length=10),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='police',
            field=models.CharField(default="'Segoe UI', sans-serif", help_text='Police CSS (ex: Roboto, Arial, Montserrat)', max_length=200),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='rayon_bord',
            field=models.CharField(default='6px', help_text='Rayon des coins (0px, 4px, 6px, 10px)', max_length=10),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='taille_texte_base',
            field=models.CharField(default='14px', help_text='Taille de base (ex: 13px, 14px, 15px)', max_length=10),
        ),
    ]
