# Generated by Django 6.0.7 on 2026-07-27 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0003_alter_organisation_couleur_texte_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisation',
            name='consignes_imputation',
            field=models.JSONField(blank=True, default=list, help_text='Liste des consignes types [{code, label}]'),
        ),
    ]
