# Generated by Django 6.0.7 on 2026-07-27 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0005_alter_organisation_consignes_imputation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organisation',
            name='consignes_imputation',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
