# Generated by Django 6.0.7 on 2026-07-28 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0006_alter_organisation_consignes_imputation'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisation',
            name='workflow_type',
            field=models.CharField(choices=[('CLASSIQUE', 'Classique (ASSIST → DG)'), ('ETENDU', 'Étendu (SGA → SG → DG)')], default='CLASSIQUE', max_length=10),
        ),
    ]
