# Generated by Django 6.0.7 on 2026-07-28 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0007_organisation_workflow_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisation',
            name='prefixe_courrier',
            field=models.CharField(blank=True, help_text='Préfixe des numéros de courrier (ex: OT, MIN-FIN). Laissez vide pour utiliser le code tenant.', max_length=10),
        ),
    ]
